const spots = [
  {
    name: "The Minor Basilica and Metropolitan Cathedral of the Immaculate Conception",
    dmsCoordinates: "14.5917° N,120.9735° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Fort Santiago",
    dmsCoordinates: "14.5942° N,120.9704° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Manila City Hall",
    dmsCoordinates: "14.5895° N,120.9816° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Paco North Cemetery",
    dmsCoordinates: "14.5810° N,120.9884° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Museum of Contemporary Art and Design",
    dmsCoordinates: "14.5628° N,120.9968° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Minor Basilica and National Shrine of Saint Lorenzo Ruiz - Binondo Church",
    dmsCoordinates: "14.6001° N,120.9746° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "San Sebastian Church",
    dmsCoordinates: "14.5997° N,120.9891° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Casa Manila",
    dmsCoordinates: "14.5894° N,120.9753° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Metropolitan Museum of Manila",
    dmsCoordinates: "14.5623° N,120.9865° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Rizal Monument",
    dmsCoordinates: "14.5818° N,120.9770° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "National Museum of Anthropology",
    dmsCoordinates: "14.5857° N,120.9812° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Minor Basilica of the Black Nazarene",
    dmsCoordinates: "14.5988° N,120.9837° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Bahay Tsinoy, Museum of Chinese in Philippine Life",
    dmsCoordinates: "14.5909° N,120.9750° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "National Museum of Natural History",
    dmsCoordinates: "14.5835° N,120.9821° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Manila Ocean Park",
    dmsCoordinates: "14.5792° N,120.9726° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Presidential Museum and Library - Malacañan Palace",
    dmsCoordinates: "14.5946° N,120.9946° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Cultural Center of the Philippines",
    dmsCoordinates: "14.5584° N,120.9859° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Manila Zoo",
    dmsCoordinates: "14.5651° N,120.9885° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Museo Pambata",
    dmsCoordinates: "14.5791° N,120.9771° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Rizal Park",
    dmsCoordinates: "14.5826° N,120.9787° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "National Museum of the Philippines",
    dmsCoordinates: "14.5869° N,120.9812° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Philippine Postal Corporation",
    dmsCoordinates: "14.5960° N,120.9792° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "San Agustin Church",
    dmsCoordinates: "14.5886° N,120.9749° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
  {
    name: "Baluarte de San Diego",
    dmsCoordinates: "14.5854° N,120.9756° E",
    description: "Edi wow po",
    rating: 4.5,
    image: "image here",
  },
];

export default spots;
